### ISSUE TITLE
Programmatically drawing

### ISSUE THREAD

**Issue by NickLarsenNZ** [abdulaziz-mohammed/whiteboardkit#1]
Hi, I really like your widget.

I'm wondering if it is possible to draw programmatically?
For example, if I had a list of paths, can I add them to the drawing?

**Comment by abdulaziz-mohammed** [comment]
Sure!
Can be easily archived by extending `WhiteboardController` class

Checkout these example implementations: 
- [gesture_whiteboard_controller.dart](https://github.com/abdulaziz-mohammed/whiteboardkit/blob/master/lib/gesture_whiteboard_controller.dart)
- [animated_sketch_controller.dart](https://github.com/abdulaziz-mohammed/whiteboardkit/blob/master/lib/animated_sketch_controller.dart)

**Comment by NickLarsenNZ** [comment]
Brilliant, thanks for the examples. Looking forward to trying this out.

**Comment by abdulaziz-mohammed** [comment]
Glad i could help. Good luck!

**Comment by yingshaoxo** [comment]
> Sure!
> Can be easily archived by extending `WhiteboardController` class
> 
> Checkout these example implementations:
> 
> * [gesture_whiteboard_controller.dart](https://github.com/abdulaziz-mohammed/whiteboardkit/blob/master/lib/gesture_whiteboard_controller.dart)
> * [animated_sketch_controller.dart](https://github.com/abdulaziz-mohammed/whiteboardkit/blob/master/lib/animated_sketch_controller.dart)

Wait a minute, sir. Where is the example code now?

I would like to help to make this library more powerful by adding some gesture stuff to match the Microsoft whiteboard app on Windows.

But I need examples.
