### ISSUE TITLE
Delay in chunk listener

### ISSUE THREAD

**Issue by surveshoeb** [abdulaziz-mohammed/whiteboardkit#4]
I'm trying to capture the chunk from **DrawingController** but it takes a minimum of 5 seconds to get updated chunk.
Is it possible to reduce that time duration?

**Comment by surveshoeb** [comment]
Any update on this issue?

**Comment by rgb1380** [comment]
Can this be opened or commented on? I get the same effect that it takes several seconds to get an updated chunk.
